server:
  port: 8080

spring:
  application:
    name: Vodostaj
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

arso:
  api:
    url: ${ARSO_API_URL}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
  sender:
    email: ${SENDGRID_SENDER_EMAIL}

vapid:
  public.key: ${VAPID_PUBLIC_KEY}
  private.key: ${VAPID_PRIVATE_KEY}
  subject: ${VAPID_SUBJECT}

logging:
  level:
    org.springframework.security: DEBUG
